### PR TITLE
Add Benchmarks and CI

### PR DESCRIPTION
**Pull request by bennypowers**
## What I did

3. Test nullable property access
2. Add a demo of nullable property access
3. Migrate benchmarks to tachometer
3. Add CI via github actions
2. Fix typos and revise README

### CODE REVIEW

**Comment by justinfagnani** [comment]
I added tests in https://github.com/justinfagnani/stampino/pull/15

I think we should port any additional tests you have here to that and move forward with the lit-html backend.

**Comment by bennypowers** [comment]
on it.

any specific reason not to use esbuild to test-ts-in-place?

**Comment by bennypowers** [comment]
I added a bunch of stuff (see edited PR description above) and changed this PR's base to lit-html branch

**Comment by justinfagnani** [comment]
> any specific reason not to use esbuild to test-ts-in-place?

What would that do? This WTR setup is pretty nice to me.

**Comment by justinfagnani** [comment]
> I added a bunch of stuff (see edited PR description above) and changed this PR's base to lit-html branch

Thanks! I'm doing a few last tests and edits of that branch, so hold tight for a sec.

**Comment by bennypowers** [comment]
> > any specific reason not to use esbuild to test-ts-in-place?
> 
> What would that do? This WTR setup is pretty nice to me.

no need to run tsc in parallel. Since you always test the source, if you had previously built with tsc, then forgot, then editted source, then tested without re-building, it can be a d'oh.

> Thanks! I'm doing a few last tests and edits of that branch, so hold tight for a sec.

I have no preference about whether to merge this into #15 or whether to merge that first and this after. Seems perhaps better the first way, but it's your call. if you like, ping me and I'll do a quick rebase.

**Comment by justinfagnani** [comment]
Oh... I didn't know deleting that branch would close this PR. Well, I just merged it to master. Can you rebase? Thanks!

**Comment by bennypowers** [comment]
See https://github.com/justinfagnani/stampino/pull/20

**Pull request closed without merging**
