### PR TITLE
fix: remove negative lookbehind

### LINKED ISSUE #28: Regexp breaks Safari
https://github.com/justinfagnani/stampino/blob/9a1e5b258e761af4041ce0b4bb76c7558e1c1693/src/stampino.ts#L385-L389
This regexp breaks on Safari

> SyntaxError: Invalid regular expression: invalid group specifier name —

### PR DESCRIPTION
**Pull request by bennypowers**
Fixes #28

### CODE REVIEW

**Comment by justinfagnani** [comment]
Yeah, the lookbehind has to go, but just removing the lookbehind broke no tests? We need more test coverage...

**Comment by bennypowers** [comment]
seemed to work for me when i tested locally in dev, and it's working like that in prod on [my demo app](https://leeway.apolloelements.dev)

I find it helps me to visualize regexp's with regexp railroad.

before:
Screen Shot 2021-07-30 at 0 35 13
which I think should mean "`{{` not preceeded by `\`"
after:
Screen Shot 2021-07-30 at 0 34 27
which I think should mean "not-`\` followed by `{{`", or "any string which does not start with `\` then immediately follows with `{{`"

**Comment by justinfagnani** [comment]
Here's a test that should be passing to check this:

```ts
  test('Attribute with binding-like separator', () => {
    const template = document.createElement('template');
    template.innerHTML = `<p foo="\\{{ x \\}}"></p>`;
    render(template, container, {x: 'foo'});
    assert.equal(
      stripExpressionMarkers(container.innerHTML),
      `<p foo="{{ x }}"></p>`
    );
  });
```

This fails though because we don't yet translate "\{{" to "{{".

So we can merge this and fix up the scanning code later.

**Comment by bennypowers** [comment]
here's a case that one could anticipate

Screen Shot 2021-07-30 at 1 04 53

so maybe we do it in 3 passes, once to replace `\{{` with some token, then again to do the real replace, then a 3rd time to replace the token?

**Comment by bennypowers** [comment]
Screen Shot 2021-07-30 at 1 04 53
this looks a little better

**Comment by bennypowers** [comment]
This looks a little more like it

Screen Shot 2021-07-30 at 1 09 53
Screen Shot 2021-07-30 at 1 14 53

**Comment by bennypowers** [comment]
After mucking around a bit, I couldn't get anything that passed all the tests.

I think we should just merge this, then come back and make a workaround for safari, like doing multiple passes or something

**Comment by justinfagnani** [comment]
I took another crack at this and I can't figure out how to match strings like `\{{ {{ x }}` correctly without either negative lookbehind or writing a little parser in JS. Considering that Safari has shipped lookbehinds for a year, and that Stampino just isn't used that much, we can just close this. If someone needs to support older Safari we could add a small parser then.

Thanks for the contribution though @bennypowers!

**Pull request closed without merging**
